import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ROLES from "../js/roles_list";
// import {admin, editor, client} from "../js/roles_list";
import { useSession, signIn, signOut } from "next-auth/react"

// const admin = 5250
// const editor = 1987
// const client = 2003


export default function Home() {
  const { data: session } = useSession()
  console.log('session, ', session);


  if(session) {
    return(<>
      {'hello' === 'hello' && (<>
        <h3> I am Hello </h3>
      </>)}

      <p>session.admin: {session.user.roles.admin}</p>
      <p>ROLES.admin {ROLES.admin}</p>
      {session.user.roles.admin === ROLES.admin && (
        <h3> I am an Admin </h3>
      )}
      {session.user.roles.editor === ROLES.editor && (
        <h3> I am an Editor </h3>
      )}
      {session.user.roles.client === ROLES.client && (
        <h3> I am an Client </h3>
      )}

    </>)
  }

  // if (session) {
  //   return (<>
  //     <div className={styles.container}>
  //       <Head>
  //         <title>Create Next App</title>
  //         <meta name="description" content="Generated by create next app" />
  //         <link rel="icon" href="/favicon.ico" />
  //       </Head>

  //       <main className={styles.main}>
  //         <h1 className={styles.title}>
  //           Welcome to <a href="https://nextjs.org">Next.js!</a>
  //         </h1>
          
  //         <h2> Signed in as {session.user.email}</h2> 
  //         <p>name: {session.user.name}</p>
  //         <p style={{color: session.user.color}}>color: {session.user.color}</p>
  //         <button onClick={() => signOut()}>Sign out</button>

  //         {session.user.roles.admin === ROLES.admin && (
  //           <h3> I am an Admin </h3>
  //         )}
  //         {session.user.roles.editor === ROLES.editor && (
  //           <h3> I am an Editor </h3>
  //         )}
  //         {session.user.roles.client === ROLES.client && (
  //           <h3> I am an Client </h3>
  //         )}
          
  //       </main>

  //       <footer className={styles.footer}>
  //         <a
  //           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           target="_blank"
  //           rel="noopener noreferrer"
  //         >
  //           Powered by{' '}
  //           <span className={styles.logo}>
  //             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //           </span>
  //         </a>
  //       </footer>
  //     </div>
  //   </>)
  // }

  return (
    <>
      <h2> Not signed in </h2>
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )
}
